# Generated by Django 3.0.1 on 2020-07-09 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200709_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_business',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='is_consumer',
            field=models.BooleanField(default=False),
        ),
    ]
