# Generated by Django 3.0.1 on 2020-07-19 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_account_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='username',
        ),
    ]
