# Generated by Django 3.0.1 on 2020-08-17 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_remove_account_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='city',
            field=models.CharField(default=1, max_length=35),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='postal',
            field=models.CharField(default=1, max_length=35),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='province',
            field=models.CharField(default=1, max_length=35),
            preserve_default=False,
        ),
    ]
