# Generated by Django 3.1 on 2020-09-07 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_remove_account_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='on_board',
            field=models.BooleanField(default=False),
        ),
    ]
