# Generated by Django 3.1 on 2020-09-25 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_clients'),
        ('business', '0057_auto_20200924_2126'),
        ('consumer', '0024_auto_20200924_2126'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Guest',
        ),
    ]
