# Generated by Django 3.1 on 2020-09-25 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_remove_clients_user'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='clients',
            constraint=models.UniqueConstraint(fields=('first_name', 'last_name', 'email'), name='unique_object'),
        ),
    ]
