# Generated by Django 3.1 on 2020-09-25 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0064_remove_company_clients'),
        ('consumer', '0034_auto_20200925_1011'),
        ('account', '0019_auto_20200925_0119'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clients',
        ),
    ]
