# Generated by Django 3.1 on 2020-09-26 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0036_auto_20200926_1910'),
        ('account', '0021_auto_20200925_1402'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clients',
        ),
    ]
