# Generated by Django 3.1 on 2020-10-16 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_auto_20201014_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_guest',
            field=models.BooleanField(default=False),
        ),
    ]
