# Generated by Django 3.1 on 2020-11-01 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_account_tz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='is_consumer',
            field=models.BooleanField(default=True),
        ),
    ]
