# Generated by Django 3.1 on 2021-02-17 01:44

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0028_account_phone_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='tz',
            field=timezone_field.fields.TimeZoneField(default='America/Toronto'),
        ),
    ]
