# Generated by Django 3.1.7 on 2021-06-08 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0032_account_rates'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='off_waitlist',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='rates',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)], default=1),
        ),
    ]
