# Generated by Django 3.1.7 on 2021-06-15 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0034_waitlistcustomers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='waitlistcustomers',
            options={'ordering': ('first_name',), 'verbose_name': 'Waitlist User', 'verbose_name_plural': 'Waitlist Users'},
        ),
        migrations.AlterUniqueTogether(
            name='waitlistcustomers',
            unique_together={('email', 'first_name')},
        ),
    ]
