# Generated by Django 3.1.7 on 2021-07-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0035_auto_20210614_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waitlistcustomers',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='waitlistcustomers',
            name='phone_code',
        ),
        migrations.AlterField(
            model_name='waitlistcustomers',
            name='first_name',
            field=models.CharField(default='', max_length=30, verbose_name='First Name'),
            preserve_default=False,
        ),
    ]
