# Generated by Django 3.0.1 on 2020-08-05 06:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0021_auto_20200727_0631'),
        ('consumer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='end',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='bookings',
            name='has_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookings',
            name='is_avail',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookings',
            name='service',
            field=models.OneToOneField(default=40, on_delete=django.db.models.deletion.CASCADE, to='business.Services'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookings',
            name='start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='ScheduleTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_slot', models.TimeField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Services')),
            ],
        ),
    ]
