# Generated by Django 3.0.1 on 2020-08-05 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0002_auto_20200805_0602'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookings',
            options={'ordering': ('service',), 'verbose_name': 'booking', 'verbose_name_plural': 'bookings'},
        ),
        migrations.DeleteModel(
            name='ScheduleTime',
        ),
    ]
