# Generated by Django 3.0.1 on 2020-08-05 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0003_auto_20200805_0258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='company',
        ),
    ]
