# Generated by Django 3.0.1 on 2020-08-05 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0022_auto_20200805_0636'),
        ('consumer', '0004_remove_bookings_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Services'),
        ),
    ]
