# Generated by Django 3.0.1 on 2020-08-05 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0022_auto_20200805_0636'),
        ('consumer', '0005_auto_20200805_0306'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='company',
            field=models.ForeignKey(default=22, on_delete=django.db.models.deletion.CASCADE, to='business.Company'),
            preserve_default=False,
        ),
    ]
