# Generated by Django 3.0.1 on 2020-08-07 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0006_bookings_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='company',
        ),
    ]
