# Generated by Django 3.0.1 on 2020-08-07 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0008_bookings_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookings',
            options={'ordering': ('start',), 'verbose_name': 'booking', 'verbose_name_plural': 'bookings'},
        ),
    ]
