# Generated by Django 3.0.1 on 2020-08-10 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0023_subcategory'),
        ('consumer', '0009_auto_20200806_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Company')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Services')),
            ],
        ),
    ]
