# Generated by Django 3.0.1 on 2020-08-16 07:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0024_company_subcategory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('consumer', '0011_auto_20200816_0327'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='reviews',
            index_together={('reviewer', 'company')},
        ),
    ]
