# Generated by Django 3.0.1 on 2020-08-17 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0013_auto_20200817_0059'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews',
            options={'ordering': ('-created',), 'verbose_name': 'Review', 'verbose_name_plural': 'Reviews'},
        ),
    ]
