# Generated by Django 3.1 on 2020-08-22 05:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('consumer', '0014_auto_20200817_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bookings',
            name='city',
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='bookings',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Last Name'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='phone',
            field=models.CharField(max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='postal',
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='bookings',
            name='province',
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
