# Generated by Django 3.1 on 2020-09-13 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0044_auto_20200913_1824'),
        ('consumer', '0017_auto_20200823_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bookings',
            name='price_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', related_query_name='bookings', to='business.services'),
        ),
    ]
