# Generated by Django 3.1 on 2020-09-14 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0018_auto_20200913_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='has_paid',
        ),
        migrations.RemoveField(
            model_name='bookings',
            name='is_avail',
        ),
    ]
