# Generated by Django 3.1 on 2020-09-15 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0019_auto_20200914_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='is_cancelled',
            field=models.BooleanField(default=True),
        ),
    ]
