# Generated by Django 3.1 on 2020-09-22 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0013_guest'),
        ('consumer', '0022_auto_20200922_0253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='address',
        ),
        migrations.RemoveField(
            model_name='bookings',
            name='city',
        ),
        migrations.RemoveField(
            model_name='bookings',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='bookings',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='bookings',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='bookings',
            name='postal',
        ),
        migrations.RemoveField(
            model_name='bookings',
            name='province',
        ),
        migrations.AddField(
            model_name='bookings',
            name='guest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.guest'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
