# Generated by Django 3.1 on 2020-09-25 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_clients'),
        ('consumer', '0023_auto_20200922_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='guest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.clients'),
        ),
    ]
