# Generated by Django 3.1 on 2020-09-25 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_auto_20200925_0119'),
        ('consumer', '0027_auto_20200925_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='guest',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.clients'),
            preserve_default=False,
        ),
    ]
