# Generated by Django 3.1 on 2020-09-25 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_auto_20200925_0119'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('consumer', '0029_remove_bookings_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='guest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.clients'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
