# Generated by Django 3.1 on 2020-09-25 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_auto_20200925_0119'),
        ('consumer', '0032_auto_20200925_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='guest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.clients'),
        ),
    ]
