# Generated by Django 3.1 on 2020-09-29 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0036_auto_20200926_1910'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews',
            options={'ordering': ('star',), 'verbose_name': 'Review', 'verbose_name_plural': 'Reviews'},
        ),
    ]
