# Generated by Django 3.1 on 2020-10-16 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0037_auto_20200928_2203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='guest',
        ),
    ]
