# Generated by Django 3.1 on 2020-10-27 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0040_extrainformation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookings',
            old_name='is_cancelled',
            new_name='is_cancelled_company',
        ),
        migrations.AddField(
            model_name='bookings',
            name='is_cancelled_user',
            field=models.BooleanField(default=False),
        ),
    ]
