# Generated by Django 3.1 on 2020-10-31 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0044_auto_20201030_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='duration_hour',
        ),
        migrations.RemoveField(
            model_name='bookings',
            name='duration_minute',
        ),
    ]
