# Generated by Django 3.1 on 2020-11-02 05:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0082_auto_20201028_0937'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('consumer', '0045_auto_20201030_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='business.company'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='guest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='business.clients'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', related_query_name='bookings', to='business.services'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='extrainformation',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='more_info', to='consumer.bookings'),
        ),
    ]
