# Generated by Django 3.1 on 2020-12-03 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0093_company_calendarics'),
        ('consumer', '0046_auto_20201102_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='business.company'),
        ),
    ]
