# Generated by Django 3.1 on 2020-12-12 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('businessadmin', '0011_auto_20201211_1900'),
        ('consumer', '0048_auto_20201211_0205'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='staffmem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='businessadmin.staffmember'),
        ),
    ]
