# Generated by Django 3.1 on 2020-12-19 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0096_auto_20201214_1821'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('consumer', '0050_auto_20201219_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='guest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.clients'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', related_query_name='bookings', to='business.services'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
