# Generated by Django 3.1 on 2020-12-19 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0052_auto_20201219_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='is_cancelled_user',
            field=models.BooleanField(default=False),
        ),
    ]
