# Generated by Django 3.1 on 2021-01-05 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('businessadmin', '0016_staffmember_pfp'),
        ('consumer', '0053_auto_20201219_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='staffmem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_bookings', to='businessadmin.staffmember'),
        ),
    ]
