# Generated by Django 3.1 on 2021-01-17 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0099_auto_20210106_2243'),
        ('consumer', '0054_auto_20210105_0341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_bookings', related_query_name='company_bookings', to='business.company'),
        ),
    ]
