# Generated by Django 3.1 on 2021-02-19 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0057_remove_bookings_time_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bookings',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
