# Generated by Django 3.1 on 2021-02-19 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0106_auto_20210218_2225'),
        ('consumer', '0058_auto_20210218_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='bookings',
            name='status',
        ),
        migrations.AddField(
            model_name='bookings',
            name='bookingreq',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_request', to='business.companyreq'),
        ),
    ]
