# Generated by Django 3.1 on 2021-02-19 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0059_auto_20210218_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='is_cancelled_request',
            field=models.BooleanField(default=False),
        ),
    ]
