# Generated by Django 3.1 on 2021-02-19 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0060_bookings_is_cancelled_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='approved',
            field=models.BooleanField(default=True),
        ),
    ]
