# Generated by Django 3.1 on 2021-02-19 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0061_bookings_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
