# Generated by Django 3.1 on 2021-02-24 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0062_auto_20210219_0214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='approved',
        ),
    ]
