# Generated by Django 3.1.7 on 2021-04-02 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0065_auto_20210326_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='paymentintent',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Payment Intent'),
        ),
    ]
