# Generated by Django 3.1.7 on 2021-05-06 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0120_auto_20210415_1334'),
        ('consumer', '0068_addonservices'),
    ]

    operations = [
        migrations.AddField(
            model_name='addonservices',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='addons_offered', to='business.company'),
            preserve_default=False,
        ),
    ]
