# Generated by Django 3.1.7 on 2021-05-06 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0120_auto_20210415_1334'),
        ('consumer', '0069_addonservices_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addonservices',
            name='services',
        ),
        migrations.AddField(
            model_name='addonservices',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='addon_offered', to='business.Services'),
        ),
    ]
