# Generated by Django 3.1.7 on 2021-05-06 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0070_auto_20210506_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='addonservices',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
