# Generated by Django 3.1.7 on 2021-05-06 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0071_addonservices_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='addon_service',
            field=models.ManyToManyField(blank=True, related_name='addon_bookings', to='consumer.AddOnServices'),
        ),
    ]
