# Generated by Django 3.1 on 2020-12-10 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0095_auto_20201210_0217'),
        ('businessadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='services',
            field=models.ManyToManyField(blank=True, to='business.Services'),
        ),
    ]
