# Generated by Django 3.1 on 2020-12-10 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businessadmin', '0002_staffmember_services'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffmember',
            options={'ordering': ('user',)},
        ),
        migrations.RemoveField(
            model_name='staffmember',
            name='address',
        ),
        migrations.RemoveField(
            model_name='staffmember',
            name='city',
        ),
        migrations.RemoveField(
            model_name='staffmember',
            name='email',
        ),
        migrations.RemoveField(
            model_name='staffmember',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='staffmember',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='staffmember',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='staffmember',
            name='postal',
        ),
        migrations.RemoveField(
            model_name='staffmember',
            name='province',
        ),
    ]
