# Generated by Django 3.1 on 2020-12-10 07:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('businessadmin', '0003_auto_20201210_0233'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffmember',
            options={},
        ),
        migrations.RemoveField(
            model_name='staffmember',
            name='user',
        ),
        migrations.AddField(
            model_name='staffmember',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
