# Generated by Django 3.1 on 2020-12-10 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businessadmin', '0004_auto_20201210_0256'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffmember',
            options={'ordering': ('company',)},
        ),
    ]
