# Generated by Django 3.1 on 2020-12-11 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessadmin', '0007_staffmember_is_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breaks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')])),
                ('from_hour', models.TimeField(default='9:00:00')),
                ('to_hour', models.TimeField(default='17:00:00')),
            ],
        ),
        migrations.AddField(
            model_name='staffmember',
            name='breaks',
            field=models.ManyToManyField(blank=True, to='businessadmin.Breaks'),
        ),
    ]
