# Generated by Django 3.1 on 2020-12-11 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('businessadmin', '0008_auto_20201211_0148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffmember',
            name='breaks',
        ),
        migrations.AddField(
            model_name='breaks',
            name='staffmember',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_breaks', to='businessadmin.staffmember'),
        ),
        migrations.AlterField(
            model_name='breaks',
            name='from_hour',
            field=models.TimeField(default='12:00:00'),
        ),
        migrations.AlterField(
            model_name='breaks',
            name='to_hour',
            field=models.TimeField(default='13:00:00'),
        ),
    ]
