# Generated by Django 3.1 on 2020-12-11 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessadmin', '0009_auto_20201211_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breaks',
            name='from_hour',
            field=models.TimeField(default='12:00 PM'),
        ),
        migrations.AlterField(
            model_name='breaks',
            name='to_hour',
            field=models.TimeField(default='1:00 PM'),
        ),
    ]
