# Generated by Django 3.1 on 2020-12-12 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businessadmin', '0010_auto_20201211_0220'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='breaks',
            options={'ordering': ('weekday',), 'verbose_name': 'Break'},
        ),
        migrations.AlterModelOptions(
            name='staffmember',
            options={'ordering': ('user',), 'verbose_name': 'Staff Member'},
        ),
    ]
