# Generated by Django 3.1 on 2020-12-14 23:21

import businessadmin.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessadmin', '0011_auto_20201211_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffmember',
            name='is_owner',
        ),
        migrations.AddField(
            model_name='staffmember',
            name='access',
            field=models.IntegerField(choices=[(0, 'Staff Access'), (1, 'Receptionist Access'), (2, 'Admin Access')], default=0),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='calendarics',
            field=models.FileField(blank=True, null=True, upload_to=businessadmin.models.calendar_staff_folder),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='cc_email',
            field=models.EmailField(blank=True, max_length=60, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='email',
            field=models.EmailField(blank=True, max_length=60, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Last Name'),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='login',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='phone',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
    ]
