# Generated by Django 3.1 on 2020-12-18 05:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('businessadmin', '0012_auto_20201214_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmember',
            name='cc_email',
            field=models.EmailField(blank=True, max_length=60, null=True, verbose_name='CC Email'),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='working_for', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='StaffWorkingHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')])),
                ('from_hour', models.TimeField(default='9:00:00')),
                ('to_hour', models.TimeField(default='17:00:00')),
                ('is_off', models.BooleanField(default=False)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_hours', to='businessadmin.staffmember')),
            ],
            options={
                'ordering': ('weekday', 'from_hour'),
                'unique_together': {('weekday', 'staff')},
            },
        ),
    ]
