# Generated by Django 3.1 on 2020-12-30 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessadmin', '0013_auto_20201218_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmember',
            name='email',
            field=models.EmailField(blank=True, max_length=60, null=True, unique=True, verbose_name='Email'),
        ),
    ]
