# Generated by Django 3.1 on 2021-01-09 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('businessadmin', '0017_auto_20210108_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmember',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='working_for', to=settings.AUTH_USER_MODEL),
        ),
    ]
