# Generated by Django 3.1 on 2021-03-16 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessadmin', '0019_staffmember_stripe_acct_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffmember',
            name='stripe_acct_id',
        ),
        migrations.AddField(
            model_name='staffmember',
            name='stripe_access_token',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Stripe Access Token'),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='stripe_user_id',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Stripe User Id'),
        ),
    ]
