# Generated by Django 3.1.7 on 2021-03-30 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessadmin', '0022_staffmember_collectpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='currency',
            field=models.CharField(choices=[('CAD', 'CAD'), ('USD', 'USD')], default='CAD', max_length=200),
        ),
    ]
