# Generated by Django 3.1.7 on 2021-03-30 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessadmin', '0023_staffmember_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='nrfpayment',
            field=models.IntegerField(default=0),
        ),
    ]
