# Generated by Django 3.1.7 on 2021-04-04 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessadmin', '0025_staffmember_collectnrfpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmember',
            name='stripe_access_token',
            field=models.CharField(blank=True, max_length=260, null=True, unique=True, verbose_name='Stripe Access Token'),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='stripe_user_id',
            field=models.CharField(blank=True, max_length=260, null=True, unique=True, verbose_name='Stripe User Id'),
        ),
    ]
