# Generated by Django 3.1.7 on 2021-06-03 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessadmin', '0028_auto_20210404_0225'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='appointment_num',
            field=models.IntegerField(choices=[(0, 'No Limit'), (1, '1 Appointment Per Day'), (2, '2 Appointments Per Day'), (3, '3 Appointments Per Day'), (4, '4 Appointments Per Day'), (5, '5 Appointments Per Day'), (6, '6 Appointments Per Day'), (7, '7 Appointments Per Day'), (8, '8 Appointments Per Day'), (9, '9 Appointments Per Day'), (10, '10 Appointments Per Day')], default=0),
        ),
    ]
