# Generated by Django 3.1 on 2020-11-02 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0082_auto_20201028_0937'),
    ]

    operations = [
        migrations.CreateModel(
            name='formBuilder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(db_index=True, max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form', to='business.company')),
            ],
        ),
    ]
