# Generated by Django 3.1 on 2020-11-03 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0046_auto_20201102_0000'),
        ('calendarapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formbuilder',
            name='company',
        ),
        migrations.AddField(
            model_name='formbuilder',
            name='booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form', to='consumer.bookings'),
        ),
        migrations.AddField(
            model_name='formbuilder',
            name='checkbox',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='formbuilder',
            name='is_required',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='formbuilder',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='formbuilder',
            name='text',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
