# Generated by Django 3.1 on 2021-01-05 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0002_auto_20201103_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='formbuilder',
            name='integer',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='formbuilder',
            name='is_integer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='formbuilder',
            name='is_required',
            field=models.BooleanField(default=False),
        ),
    ]
