# Generated by Django 3.1 on 2021-01-19 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0055_auto_20210117_0813'),
        ('business', '0099_auto_20210106_2243'),
        ('calendarapp', '0006_auto_20210119_0818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formbuilder',
            name='booking',
        ),
        migrations.AddField(
            model_name='formbuilder',
            name='booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_form', to='consumer.bookings'),
        ),
        migrations.RemoveField(
            model_name='formbuilder',
            name='services',
        ),
        migrations.AddField(
            model_name='formbuilder',
            name='services',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forms_attached', to='business.services'),
        ),
    ]
