# Generated by Django 3.1 on 2021-01-19 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0055_auto_20210117_0813'),
        ('calendarapp', '0007_auto_20210119_0844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formbuilder',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='formbuilder',
            name='services',
        ),
        migrations.AddField(
            model_name='formbuilder',
            name='is_text',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.CreateModel(
            name='bookingForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_form', to='consumer.bookings')),
                ('form', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_form', to='calendarapp.formbuilder')),
            ],
        ),
    ]
