# Generated by Django 3.1 on 2021-01-19 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0009_auto_20210119_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formbuilder',
            name='checkbox',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='formbuilder',
            name='is_text',
            field=models.BooleanField(default=False),
        ),
    ]
