# Generated by Django 3.1 on 2021-01-19 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0099_auto_20210106_2243'),
        ('calendarapp', '0010_auto_20210119_0903'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formbuilder',
            old_name='checkbox',
            new_name='is_checkbox',
        ),
        migrations.RemoveField(
            model_name='formbuilder',
            name='integer',
        ),
        migrations.RemoveField(
            model_name='formbuilder',
            name='text',
        ),
        migrations.AddField(
            model_name='bookingform',
            name='checkbox',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookingform',
            name='integer',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookingform',
            name='text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='formbuilder',
            name='services',
            field=models.ManyToManyField(to='business.Services'),
        ),
        migrations.AlterField(
            model_name='bookingform',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_form', to='calendarapp.formbuilder'),
        ),
        migrations.AlterField(
            model_name='formbuilder',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_forms', to='business.company'),
        ),
        migrations.AlterField(
            model_name='formbuilder',
            name='is_text',
            field=models.BooleanField(default=True),
        ),
    ]
