# Generated by Django 3.1 on 2021-01-19 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0055_auto_20210117_0813'),
        ('calendarapp', '0011_auto_20210119_0919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingform',
            name='form',
        ),
        migrations.AddField(
            model_name='bookingform',
            name='label',
            field=models.CharField(default='Label', max_length=50),
        ),
        migrations.AlterField(
            model_name='bookingform',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_form', to='consumer.bookings'),
        ),
    ]
