# Generated by Django 3.1 on 2021-01-25 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0099_auto_20210106_2243'),
        ('calendarapp', '0013_auto_20210124_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formbuilder',
            name='services',
            field=models.ManyToManyField(related_name='service_forms', to='business.Services'),
        ),
    ]
