# Generated by Django 3.1 on 2021-01-25 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0055_auto_20210117_0813'),
        ('business', '0099_auto_20210106_2243'),
        ('calendarapp', '0014_auto_20210124_2304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formbuilder',
            options={'ordering': ['label']},
        ),
        migrations.AlterField(
            model_name='bookingform',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_forms', to='consumer.bookings'),
        ),
        migrations.AlterField(
            model_name='bookingform',
            name='label',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='formbuilder',
            name='services',
            field=models.ManyToManyField(blank=True, null=True, related_name='service_forms', to='business.Services'),
        ),
    ]
