# Generated by Django 3.1 on 2021-01-25 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0099_auto_20210106_2243'),
        ('calendarapp', '0015_auto_20210125_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formbuilder',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='service_forms', to='business.Services'),
        ),
    ]
