# Generated by Django 3.1 on 2021-01-25 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0016_auto_20210125_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingform',
            name='label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='formbuilder',
            name='label',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
