# Generated by Django 3.1 on 2021-01-28 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0017_auto_20210125_0136'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formbuilder',
            options={'ordering': ['order']},
        ),
    ]
