# Generated by Django 3.1 on 2021-03-10 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0114_auto_20210310_0315'),
        ('calendarapp', '0018_auto_20210128_0317'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingPageViews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directmonthly', models.PositiveIntegerField(default=0)),
                ('directweekly', models.PositiveIntegerField(default=0)),
                ('directtotal', models.PositiveIntegerField(default=0)),
                ('kijiji', models.PositiveIntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_views', to='business.company')),
            ],
        ),
    ]
