# Generated by Django 3.1 on 2021-03-10 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0019_bookingpageviews'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookingPageViews',
        ),
    ]
