# Generated by Django 3.1.7 on 2021-05-22 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productadmin', '0001_initial'),
    ]

    operations = [
        # migrations.AlterUniqueTogether(
        #     name='shippingzone',
        #     unique_together=None,
        # ),
        # migrations.RemoveField(
        #     model_name='shippingzone',
        #     name='city',
        # ),
        # migrations.RemoveField(
        #     model_name='shippingzone',
        #     name='company',
        # ),
        # migrations.RemoveField(
        #     model_name='shippingzone',
        #     name='state',
        # ),
        migrations.DeleteModel(
            name='PriceBasedShippingRate',
        ),
        # migrations.DeleteModel(
        #     name='ShippingZone',
        # ),
    ]
