# Generated by Django 3.1.7 on 2021-05-22 01:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.CITIES_CITY_MODEL),
        ('business', '0121_auto_20210520_1642'),
        ('cities', '0011_auto_20180108_0706'),
        ('productadmin', '0004_pricebasedshippingrate'),
    ]

    # operations = [
    #     migrations.RenameModel(
    #         old_name='CompanyShippingZone',
    #         new_name='ShippingZone',
    #     ),
    # ]
