# Generated by Django 3.1.7 on 2021-05-22 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productadmin', '0005_auto_20210521_2132'),
    ]

    # operations = [
    #     migrations.DeleteModel(
    #         name='ShippingZone',
    #     ),
    # ]
