# Generated by Django 3.1.7 on 2021-05-22 01:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.CITIES_CITY_MODEL),
        ('cities', '0011_auto_20180108_0706'),
        ('business', '0121_auto_20210520_1642'),
        ('productadmin', '0007_delete_companyshippingzone'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyShippingZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('postal_code', models.CharField(max_length=20)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.CITIES_CITY_MODEL, verbose_name='City')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipping_offered', to='business.company')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cities.region', verbose_name='State or Province')),
            ],
            options={
                'verbose_name': 'Shipping Zone',
                'verbose_name_plural': 'Shipping Zone',
                'ordering': ('company',),
                'unique_together': {('company', 'name')},
            },
        ),
        # migrations.DeleteModel(
        #     name='ShippingZone',
        # ),
    ]
