# Generated by Django 3.1.7 on 2021-05-22 01:47

from django.conf import settings
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.CITIES_CITY_MODEL),
        ('cities', '0011_auto_20180108_0706'),
        ('productadmin', '0008_auto_20210521_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyshippingzone',
            name='city',
        ),
        migrations.AddField(
            model_name='companyshippingzone',
            name='city',
            field=models.ManyToManyField(to=settings.CITIES_CITY_MODEL, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='companyshippingzone',
            name='country',
            field=django_countries.fields.CountryField(max_length=746, multiple=True),
        ),
        migrations.RemoveField(
            model_name='companyshippingzone',
            name='state',
        ),
        migrations.AddField(
            model_name='companyshippingzone',
            name='state',
            field=models.ManyToManyField(to='cities.Region', verbose_name='State or Province'),
        ),
        # migrations.DeleteModel(
        #     name='ShippingZone',
        # ),
    ]
