# Generated by Django 3.1.7 on 2021-05-22 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productadmin', '0010_auto_20210521_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyshippingzone',
            name='pricebased_rate',
            field=models.ManyToManyField(related_name='pricebased_rates', to='productadmin.PriceBasedShippingRate'),
        ),
    ]
