# Generated by Django 3.1.7 on 2021-05-22 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productadmin', '0011_companyshippingzone_pricebased_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyshippingzone',
            name='pricebased_rate',
            field=models.ManyToManyField(blank=True, related_name='pricebased_rates', to='productadmin.PriceBasedShippingRate'),
        ),
    ]
