# Generated by Django 3.1.7 on 2021-05-22 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productadmin', '0012_auto_20210521_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricebasedshippingrate',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
