# Generated by Django 3.1.7 on 2021-05-22 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0121_auto_20210520_1642'),
        ('productadmin', '0014_auto_20210521_2340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricebasedshippingrate',
            options={'ordering': ('company',), 'verbose_name': 'Shipping Zone', 'verbose_name_plural': 'Shipping Zone'},
        ),
        migrations.AlterField(
            model_name='companyshippingzone',
            name='name',
            field=models.CharField(max_length=200, verbose_name=''),
        ),
        migrations.AlterUniqueTogether(
            name='companyshippingzone',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='pricebasedshippingrate',
            unique_together={('company', 'name')},
        ),
    ]
