# Generated by Django 3.1.7 on 2021-05-22 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0121_auto_20210520_1642'),
        ('productadmin', '0015_auto_20210522_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyshippingzone',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipping_zones_avail', to='business.company'),
        ),
        migrations.AlterField(
            model_name='companyshippingzone',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='pricebasedshippingrate',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipping_pricebased', to='business.company'),
        ),
    ]
