# Generated by Django 3.1.7 on 2021-05-22 20:42

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productadmin', '0016_auto_20210522_0202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricebasedshippingrate',
            options={'ordering': ('company',), 'verbose_name': 'Price Based Shipping Rate', 'verbose_name_plural': 'Price Based Shipping Rates'},
        ),
        # migrations.AddField(
        #     model_name='pricebasedshippingrate',
        #     name='names',
        #     field=models.CharField(blank=True, max_length=200, null=True, verbose_name=''),
        # ),
        migrations.AlterField(
            model_name='pricebasedshippingrate',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Rate Amount'),
        ),
        # migrations.AlterUniqueTogether(
        #     name='pricebasedshippingrate',
        #     unique_together=set(),
        # ),
        # migrations.RemoveField(
        #     model_name='pricebasedshippingrate',
        #     name='name',
        # ),
    ]
