# Generated by Django 3.1.7 on 2021-05-22 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0121_auto_20210520_1642'),
        ('productadmin', '0018_auto_20210522_1653'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pricebasedshippingrate',
            unique_together={('company', 'names')},
        ),
    ]
