# Generated by Django 3.0.1 on 2020-07-09 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='category',
        ),
        migrations.AddField(
            model_name='company',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, related_name='companies', to='business.Category'),
        ),
    ]
