# Generated by Django 3.0.1 on 2020-07-09 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_auto_20200709_0731'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ('user',), 'verbose_name': 'company', 'verbose_name_plural': 'companies'},
        ),
        migrations.RemoveField(
            model_name='company',
            name='business_name',
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(max_length=200),
        ),
    ]
