# Generated by Django 3.0.1 on 2020-07-09 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_auto_20200709_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='email',
        ),
    ]
