# Generated by Django 3.0.1 on 2020-07-09 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_remove_company_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='phone',
        ),
    ]
