# Generated by Django 3.0.1 on 2020-07-11 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_remove_company_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='tags',
        ),
    ]
