# Generated by Django 3.0.1 on 2020-07-16 01:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0010_auto_20200712_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='postal',
            field=models.CharField(default=1, max_length=10, validators=[django.core.validators.RegexValidator(regex='/([ABCEGHJKLMNPRSTVXY]\\d)([ABCEGHJKLMNPRSTVWXYZ]\\d){2}/i')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='state',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
