# Generated by Django 3.0.1 on 2020-07-18 20:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0011_auto_20200716_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='postal',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(regex='^[ABCEGHJKLMNPRSTVXY]{1}\\d{1}[A-Z]{1} *\\d{1}[A-Z]{1}\\d{1}$')]),
        ),
    ]
