# Generated by Django 3.0.1 on 2020-07-18 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0013_auto_20200718_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='business_name',
            field=models.CharField(db_index=True, default=1, max_length=30),
            preserve_default=False,
        ),
    ]
