# Generated by Django 3.0.1 on 2020-07-23 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0015_auto_20200718_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='price_type',
            field=models.CharField(choices=[('fixed', 'Fixed'), ('start', 'Starting Price'), ('variable', 'Variable'), ('dont', "Don't Show"), ('free', 'Free')], default='fixed', max_length=10),
        ),
    ]
