# Generated by Django 3.0.1 on 2020-07-23 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0016_services_price_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='duration_hour',
            field=models.CharField(choices=[('zero', '0 hours'), ('one', '1 hour'), ('two', '2 hours'), ('three', '3 hours'), ('four', '4 hours'), ('five', '5 hours'), ('six', '6 hours'), ('seven', '7 hours'), ('eight', '8 hours'), ('nine', '9 hours'), ('ten', '10 hours'), ('eleven', '11 hours'), ('twelve', '12 hours'), ('thirteen', '13 hours'), ('fourteen', '14 hours'), ('fifteen', '1 hours'), ('sixteen', '1 hours'), ('seventeen', '1 hours'), ('eighteen', '1 hours'), ('nineteen', '1 hours'), ('twenty', '1 hours'), ('twentyone', '1 hours'), ('twentytwo', '1 hours'), ('twentythree', '1 hours')], default='zero', max_length=11),
        ),
        migrations.AddField(
            model_name='services',
            name='duration_minute',
            field=models.CharField(choices=[('zero', '0 minutes'), ('five', '5 minutes'), ('ten', '10 minutes'), ('fifteen', '15 minutes'), ('twenty', '20 minutes'), ('twentyfive', '25 minutes'), ('thirty', '30 minutes'), ('thirtyfive', '35 minutes'), ('fourty', '40 minutes'), ('fourtyfive', '45 minutes'), ('fifty', '50 minutes'), ('fiftyfive', '55 minutes')], default='zero', max_length=11),
        ),
    ]
