# Generated by Django 3.0.1 on 2020-07-23 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0017_auto_20200723_0549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='description',
            field=models.TextField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='services',
            name='duration_hour',
            field=models.CharField(choices=[('zero', '0 hours'), ('one', '1 hour'), ('two', '2 hours'), ('three', '3 hours'), ('four', '4 hours'), ('five', '5 hours'), ('six', '6 hours'), ('seven', '7 hours'), ('eight', '8 hours'), ('nine', '9 hours'), ('ten', '10 hours'), ('eleven', '11 hours'), ('twelve', '12 hours'), ('thirteen', '13 hours'), ('fourteen', '14 hours'), ('fifteen', '15 hours'), ('sixteen', '16 hours'), ('seventeen', '17 hours'), ('eighteen', '18 hours'), ('nineteen', '19 hours'), ('twenty', '20 hours'), ('twentyone', '21 hours'), ('twentytwo', '22 hours'), ('twentythree', '23 hours')], default='zero', max_length=11),
        ),
    ]
