# Generated by Django 3.0.1 on 2020-07-24 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0018_auto_20200723_0603'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='checkintime',
            field=models.CharField(choices=[('zero', '0 minutes'), ('five', '5 minutes'), ('ten', '10 minutes'), ('fifteen', '15 minutes'), ('twenty', '20 minutes'), ('twentyfive', '25 minutes'), ('thirty', '30 minutes'), ('thirtyfive', '35 minutes'), ('fourty', '40 minutes'), ('fourtyfive', '45 minutes'), ('fifty', '50 minutes'), ('fiftyfive', '55 minutes')], default='zero', max_length=10),
        ),
        migrations.AddField(
            model_name='services',
            name='padding',
            field=models.CharField(choices=[('none', '-'), ('before', 'Before'), ('after', 'After'), ('bf', 'Before & After')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='services',
            name='paddingtime_hour',
            field=models.CharField(choices=[('zero', '0 minutes'), ('five', '5 minutes'), ('ten', '10 minutes'), ('fifteen', '15 minutes'), ('twenty', '20 minutes'), ('twentyfive', '25 minutes'), ('thirty', '30 minutes'), ('thirtyfive', '35 minutes'), ('fourty', '40 minutes'), ('fourtyfive', '45 minutes'), ('fifty', '50 minutes'), ('fiftyfive', '55 minutes')], default='zero', max_length=10),
        ),
        migrations.AddField(
            model_name='services',
            name='paddingtime_minute',
            field=models.CharField(choices=[('zero', '0 minutes'), ('five', '5 minutes'), ('ten', '10 minutes'), ('fifteen', '15 minutes'), ('twenty', '20 minutes'), ('twentyfive', '25 minutes'), ('thirty', '30 minutes'), ('thirtyfive', '35 minutes'), ('fourty', '40 minutes'), ('fourtyfive', '45 minutes'), ('fifty', '50 minutes'), ('fiftyfive', '55 minutes')], default='zero', max_length=10),
        ),
    ]
