# Generated by Django 3.0.1 on 2020-07-27 06:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0020_auto_20200726_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='postal',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='A valid postal code/ZIP Code must be entered', regex='^[ABCEGHJKLMNPRSTVXY]{1}\\d{1}[A-Z]{1} *\\d{1}[A-Z]{1}\\d{1}$')]),
        ),
    ]
