# Generated by Django 3.0.1 on 2020-08-10 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0023_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='subcategory',
            field=models.ManyToManyField(to='business.SubCategory'),
        ),
    ]
