# Generated by Django 3.1 on 2020-08-20 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0029_auto_20200820_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='business_hour',
        ),
        migrations.DeleteModel(
            name='OpeningHours',
        ),
    ]
