# Generated by Django 3.1 on 2020-08-21 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0032_company_interval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='interval',
            field=models.IntegerField(choices=[(0, '0 Minutes'), (5, '5 Minutes'), (10, '10 Minutes'), (15, '15 Minutes'), (20, '20 Minutes'), (25, '25 Minutes'), (30, '30 Minutes'), (35, '35 Minutes'), (40, '40 Minutes'), (45, '45 Minutes'), (50, '50 Minutes'), (55, '55 Minutes')], default=1),
        ),
        migrations.AlterField(
            model_name='services',
            name='checkintime',
            field=models.IntegerField(choices=[(0, '0 Minutes'), (5, '5 Minutes'), (10, '10 Minutes'), (15, '15 Minutes'), (20, '20 Minutes'), (25, '25 Minutes'), (30, '30 Minutes'), (35, '35 Minutes'), (40, '40 Minutes'), (45, '45 Minutes'), (50, '50 Minutes'), (55, '55 Minutes')], default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='services',
            name='duration_hour',
            field=models.IntegerField(choices=[(0, '0 Hours'), (1, '1 Hour'), (2, '2 Hours'), (3, '3 Hours'), (4, '4 Hours'), (5, '5 Hours'), (6, '6 Hours'), (7, '7 Hours'), (8, '8 Hours'), (9, '9 Hours'), (10, '10 Hours'), (11, '11 Hours'), (12, '12 Hours'), (13, '13 Hours'), (14, '14 Hours'), (15, '15 Hours'), (16, '16 Hours'), (17, '17 Hours'), (18, '18 Hours'), (19, '19 Hours'), (20, '20 Hours'), (21, '21 Hours'), (22, '22 Hours'), (23, '23 Hours')], default=0, max_length=11),
        ),
        migrations.AlterField(
            model_name='services',
            name='duration_minute',
            field=models.IntegerField(choices=[(0, '0 Minutes'), (5, '5 Minutes'), (10, '10 Minutes'), (15, '15 Minutes'), (20, '20 Minutes'), (25, '25 Minutes'), (30, '30 Minutes'), (35, '35 Minutes'), (40, '40 Minutes'), (45, '45 Minutes'), (50, '50 Minutes'), (55, '55 Minutes')], default=5, max_length=11),
        ),
        migrations.AlterField(
            model_name='services',
            name='padding',
            field=models.IntegerField(choices=[('none', '-'), ('before', 'Before'), ('after', 'After'), ('bf', 'Before & After')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='services',
            name='paddingtime_hour',
            field=models.IntegerField(choices=[(0, '0 Hours'), (1, '1 Hour'), (2, '2 Hours'), (3, '3 Hours'), (4, '4 Hours'), (5, '5 Hours'), (6, '6 Hours'), (7, '7 Hours'), (8, '8 Hours'), (9, '9 Hours'), (10, '10 Hours'), (11, '11 Hours'), (12, '12 Hours'), (13, '13 Hours'), (14, '14 Hours'), (15, '15 Hours'), (16, '16 Hours'), (17, '17 Hours'), (18, '18 Hours'), (19, '19 Hours'), (20, '20 Hours'), (21, '21 Hours'), (22, '22 Hours'), (23, '23 Hours')], default=0, max_length=11),
        ),
        migrations.AlterField(
            model_name='services',
            name='paddingtime_minute',
            field=models.IntegerField(choices=[(0, '0 Minutes'), (5, '5 Minutes'), (10, '10 Minutes'), (15, '15 Minutes'), (20, '20 Minutes'), (25, '25 Minutes'), (30, '30 Minutes'), (35, '35 Minutes'), (40, '40 Minutes'), (45, '45 Minutes'), (50, '50 Minutes'), (55, '55 Minutes')], default=0, max_length=10),
        ),
    ]
