# Generated by Django 3.1 on 2020-08-21 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0034_auto_20200820_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='padding',
            field=models.CharField(choices=[('none', '-'), ('before', 'Before'), ('after', 'After'), ('bf', 'Before & After')], default='none', max_length=20),
        ),
    ]
