# Generated by Django 3.1 on 2020-09-03 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0040_auto_20200902_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True, db_index=True, max_length=500),
        ),
    ]
