# Generated by Django 3.1 on 2020-09-03 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0041_auto_20200903_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=10),
        ),
    ]
