# Generated by Django 3.1 on 2020-09-12 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0042_auto_20200903_0937'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ('category',), 'verbose_name': 'sub-category', 'verbose_name_plural': 'sub-categories'},
        ),
        migrations.AddField(
            model_name='company',
            name='cancellation',
            field=models.IntegerField(choices=[('0', 'Anytime'), ('1', '1 hour'), ('3', '3 hours'), ('6', '6 hours'), ('8', '8 hours'), ('12', '12 hours'), ('24', '1 day'), ('48', '2 days'), ('72', '3 days'), ('96', '4 days'), ('168', '1 week'), ('10000', 'never')], default='0'),
        ),
        migrations.AddField(
            model_name='company',
            name='notes',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='returning',
            field=models.BooleanField(default=False),
        ),
    ]
