# Generated by Django 3.1 on 2020-09-13 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0043_auto_20200912_0534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='cancellation',
            field=models.IntegerField(choices=[(0, 'Anytime'), (1, '1 hour'), (3, '3 hours'), (6, '6 hours'), (8, '8 hours'), (12, '12 hours'), (24, '1 day'), (48, '2 days'), (72, '3 days'), (96, '4 days'), (168, '1 week'), (10000, 'never')], default='0'),
        ),
        migrations.AlterField(
            model_name='company',
            name='interval',
            field=models.IntegerField(choices=[(5, '5 Minutes'), (10, '10 Minutes'), (15, '15 Minutes'), (20, '20 Minutes'), (25, '25 Minutes'), (30, '30 Minutes'), (35, '35 Minutes'), (40, '40 Minutes'), (45, '45 Minutes'), (50, '50 Minutes'), (55, '55 Minutes')], default=1),
        ),
        migrations.AlterField(
            model_name='company',
            name='notes',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
