# Generated by Django 3.1 on 2020-09-16 03:09

import business.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0044_auto_20200913_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='image',
            field=models.ImageField(blank=True, upload_to=business.models.get_user_image_folder),
        ),
    ]
