# Generated by Django 3.1 on 2020-09-17 03:27

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('business', '0045_auto_20200915_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
