# Generated by Django 3.1 on 2020-09-19 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0046_company_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='fb_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='instagram_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='twitter_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
