# Generated by Django 3.1 on 2020-09-19 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0047_auto_20200919_0138'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='website_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
