# Generated by Django 3.1 on 2020-09-19 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0051_auto_20200919_0304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='email',
        ),
    ]
