# Generated by Django 3.1 on 2020-09-22 06:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0013_guest'),
        ('business', '0055_auto_20200920_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='clients',
            field=models.ManyToManyField(related_name='clients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='company',
            name='guest_client',
            field=models.ManyToManyField(related_name='guest_clients', to='account.Guest'),
        ),
        migrations.AlterField(
            model_name='services',
            name='description',
            field=models.TextField(db_index=True, max_length=250),
        ),
    ]
