# Generated by Django 3.1 on 2020-09-25 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0057_auto_20200924_2126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='clients',
        ),
    ]
