# Generated by Django 3.1 on 2020-09-25 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_auto_20200925_0119'),
        ('business', '0062_auto_20200925_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='clients',
            field=models.ManyToManyField(related_name='clients', to='account.Clients'),
        ),
    ]
