# Generated by Django 3.1 on 2020-09-26 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0065_company_clients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='clients',
        ),
    ]
