# Generated by Django 3.1 on 2020-09-26 23:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0066_remove_company_clients'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Last Name')),
                ('email', models.EmailField(db_index=True, max_length=60, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('postal', models.CharField(blank=True, max_length=35, null=True)),
                ('province', models.CharField(blank=True, max_length=35, null=True)),
                ('city', models.CharField(blank=True, max_length=35, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='business.company')),
            ],
            options={
                'unique_together': {('company', 'email')},
            },
        ),
    ]
