# Generated by Django 3.1 on 2020-09-26 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0067_clients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='email',
            field=models.EmailField(max_length=60, verbose_name='Email'),
        ),
        migrations.AlterUniqueTogether(
            name='clients',
            unique_together=set(),
        ),
    ]
