# Generated by Django 3.1 on 2020-10-06 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0070_company_users_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='emailReminders',
            field=models.BooleanField(default=True),
        ),
    ]
