# Generated by Django 3.1 on 2020-10-06 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0071_company_emailreminders'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='shownotes',
            field=models.BooleanField(default=False),
        ),
    ]
