# Generated by Django 3.1 on 2020-10-11 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0075_companyreq'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyreq',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
