# Generated by Django 3.1 on 2020-10-11 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0076_companyreq_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ('-updated',), 'verbose_name': 'company', 'verbose_name_plural': 'companies'},
        ),
        migrations.AlterModelOptions(
            name='companyreq',
            options={'ordering': ('created_at',), 'verbose_name': 'Request For Company'},
        ),
        migrations.AlterField(
            model_name='companyreq',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
