# Generated by Django 3.1 on 2020-10-11 19:59

import business.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0077_auto_20201011_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyreq',
            name='add_to_list',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companyreq',
            name='description',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companyreq',
            name='image',
            field=models.ImageField(blank=True, upload_to=business.models.get_user_image_folder),
        ),
    ]
