# Generated by Django 3.1 on 2020-10-11 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0078_auto_20201011_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyreq',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
