# Generated by Django 3.1 on 2020-10-28 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0081_auto_20201023_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyreq',
            name='description',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
