# Generated by Django 3.1 on 2020-11-02 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0082_auto_20201028_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='confirmation_minutes',
            field=models.IntegerField(choices=[(0, '0 Minutes'), (5, '5 Minutes'), (10, '10 Minutes'), (15, '15 Minutes'), (20, '20 Minutes'), (25, '25 Minutes'), (30, '30 Minutes'), (35, '35 Minutes'), (40, '40 Minutes'), (45, '45 Minutes'), (50, '50 Minutes'), (55, '55 Minutes')], default=15),
        ),
    ]
