# Generated by Django 3.1 on 2020-11-05 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0083_company_confirmation_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='showAddress',
            field=models.BooleanField(default=True),
        ),
    ]
