# Generated by Django 3.1 on 2020-11-11 08:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0084_company_showaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='postal',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='A valid postal code/ZIP Code must be entered, letters must be in all caps', regex='^[ABCEGHJKLMNPRSTVXYabcdefghijklmnopqrstuvwxyz]{1}\\d{1}[A-Z]{1} *\\d{1}[A-Z]{1}\\d{1}$')]),
        ),
    ]
