# Generated by Django 3.1 on 2020-11-19 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0087_servicecategories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecategories',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_category', to='business.company'),
        ),
    ]
