# Generated by Django 3.1 on 2020-11-28 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0088_auto_20201119_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecategories',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_category', to='business.company'),
        ),
        migrations.AlterField(
            model_name='servicecategories',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
