# Generated by Django 3.1 on 2020-11-28 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0089_auto_20201127_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecategories',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_category', to='business.company'),
        ),
        migrations.AlterField(
            model_name='servicecategories',
            name='services',
            field=models.ManyToManyField(blank=True, null=True, to='business.Services'),
        ),
    ]
