# Generated by Django 3.1 on 2020-11-28 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0090_auto_20201127_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecategories',
            name='services',
            field=models.ManyToManyField(blank=True, to='business.Services'),
        ),
    ]
