# Generated by Django 3.1 on 2020-12-03 23:26

import business.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0092_auto_20201130_0313'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='calendarics',
            field=models.FileField(blank=True, null=True, upload_to=business.models.calendar_folder),
        ),
    ]
