# Generated by Django 3.1 on 2020-12-10 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0094_auto_20201208_0211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clients',
            options={'ordering': ('first_name',)},
        ),
    ]
