# Generated by Django 3.1 on 2020-12-14 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0095_auto_20201210_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='darkmode',
            field=models.BooleanField(default=False),
        ),
    ]
