# Generated by Django 3.1 on 2020-12-20 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0096_auto_20201214_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='email',
            field=models.EmailField(blank=True, max_length=60, null=True, verbose_name='Email'),
        ),
    ]
