# Generated by Django 3.1 on 2021-01-07 03:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0098_clients_phone_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='phone',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message='Please enter a 10 digit Phone Number.', regex='^\\+?1?\\d{10,10}$')]),
        ),
    ]
