# Generated by Django 3.1 on 2021-02-10 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0099_auto_20210106_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='postal',
            field=models.CharField(max_length=10),
        ),
    ]
