# Generated by Django 3.1 on 2021-02-10 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0100_auto_20210210_0234'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='background',
            field=models.CharField(choices=[('primary', 'primary'), ('carbon', 'carbon'), ('hexagon', 'hexagon')], default='primary', max_length=200),
        ),
    ]
