# Generated by Django 3.1 on 2021-02-17 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0102_auto_20210216_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='subscriptionplan',
            field=models.IntegerField(choices=[(0, 'Free'), (1, 'Pro'), (2, 'Premium')], default=0),
        ),
    ]
