# Generated by Django 3.1 on 2021-02-19 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0104_auto_20210217_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='request',
            field=models.BooleanField(default=False),
        ),
    ]
