# Generated by Django 3.1 on 2021-02-19 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0105_services_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyreq',
            name='approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='companyreq',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
