# Generated by Django 3.1 on 2021-02-19 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0106_auto_20210218_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyreq',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='companyreq',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
