# Generated by Django 3.1 on 2021-02-19 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0107_auto_20210218_2231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyreq',
            old_name='add_to_list',
            new_name='is_addusertolist',
        ),
        migrations.AddField(
            model_name='companyreq',
            name='is_addbooking',
            field=models.BooleanField(default=False),
        ),
    ]
