# Generated by Django 3.1 on 2021-02-19 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0108_auto_20210218_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyreq',
            name='description',
        ),
        migrations.RemoveField(
            model_name='companyreq',
            name='image',
        ),
    ]
