# Generated by Django 3.1 on 2021-02-19 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0109_auto_20210219_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyreq',
            name='guest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requestguest', to='business.clients'),
        ),
        migrations.AlterField(
            model_name='companyreq',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requestsuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
