# Generated by Django 3.1 on 2021-03-02 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0110_auto_20210219_0201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyreq',
            name='approved',
        ),
    ]
