# Generated by Django 3.1 on 2021-03-10 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0111_remove_companyreq_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='after_window_day',
            field=models.IntegerField(choices=[('0', '0 Day'), ('1', '1 Day'), ('2', '2 Days'), ('3', '3 Days'), ('4', '4 Days'), ('5', '5 Days'), ('6', '6 Days'), ('7', '7 Days'), ('8', '8 Days'), ('9', '9 Days'), ('10', '10 Days'), ('11', '11 Days'), ('12', '12 Days'), ('13', '13 Days'), ('14', '14 Days'), ('15', '15 Days'), ('16', '16 Days'), ('17', '17 Days'), ('18', '18 Days'), ('19', '19 Days'), ('20', '20 Days'), ('21', '21 Days'), ('22', '22 Days'), ('23', '23 Days'), ('24', '24 Days'), ('25', '25 Days'), ('26', '26 Days'), ('27', '27 Days'), ('28', '28 Days'), ('29', '29 Days')], default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='after_window_month',
            field=models.IntegerField(choices=[('0', '0 Month'), ('1', '1 Month'), ('2', '2 Months'), ('3', '3 Months'), ('4', '4 Months'), ('5', '5 Months'), ('6', '6 Months'), ('7', '7 Months'), ('8', '8 Months'), ('9', '9 Months'), ('10', '10 Months'), ('11', '11 Months'), ('12', '12 Months')], default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='before_window_day',
            field=models.IntegerField(choices=[('0', '0 Day'), ('1', '1 Day'), ('2', '2 Days'), ('3', '3 Days'), ('4', '4 Days'), ('5', '5 Days'), ('6', '6 Days'), ('7', '7 Days'), ('8', '8 Days'), ('9', '9 Days'), ('10', '10 Days'), ('11', '11 Days'), ('12', '12 Days'), ('13', '13 Days'), ('14', '14 Days'), ('15', '15 Days'), ('16', '16 Days'), ('17', '17 Days'), ('18', '18 Days'), ('19', '19 Days'), ('20', '20 Days'), ('21', '21 Days'), ('22', '22 Days'), ('23', '23 Days'), ('24', '24 Days'), ('25', '25 Days'), ('26', '26 Days'), ('27', '27 Days'), ('28', '28 Days'), ('29', '29 Days')], default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='before_window_hour',
            field=models.IntegerField(choices=[(0, '0 Hours'), (1, '1 Hour'), (2, '2 Hours'), (3, '3 Hours'), (4, '4 Hours'), (5, '5 Hours'), (6, '6 Hours'), (7, '7 Hours'), (8, '8 Hours'), (9, '9 Hours'), (10, '10 Hours'), (11, '11 Hours'), (12, '12 Hours'), (13, '13 Hours'), (14, '14 Hours'), (15, '15 Hours'), (16, '16 Hours'), (17, '17 Hours'), (18, '18 Hours'), (19, '19 Hours'), (20, '20 Hours'), (21, '21 Hours'), (22, '22 Hours'), (23, '23 Hours')], default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='before_window_min',
            field=models.IntegerField(choices=[(0, '0 Minutes'), (5, '5 Minutes'), (10, '10 Minutes'), (15, '15 Minutes'), (20, '20 Minutes'), (25, '25 Minutes'), (30, '30 Minutes'), (35, '35 Minutes'), (40, '40 Minutes'), (45, '45 Minutes'), (50, '50 Minutes'), (55, '55 Minutes')], default=0),
        ),
    ]
