# Generated by Django 3.1 on 2021-03-10 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0113_auto_20210310_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='after_window_day',
            field=models.IntegerField(choices=[(0, '0 Day'), (1, '1 Day'), (2, '2 Days'), (3, '3 Days'), (4, '4 Days'), (5, '5 Days'), (6, '6 Days'), (7, '7 Days'), (8, '8 Days'), (9, '9 Days'), (10, '10 Days'), (11, '11 Days'), (12, '12 Days'), (13, '13 Days'), (14, '14 Days'), (15, '15 Days'), (16, '16 Days'), (17, '17 Days'), (18, '18 Days'), (19, '19 Days'), (20, '20 Days'), (21, '21 Days'), (22, '22 Days'), (23, '23 Days'), (24, '24 Days'), (25, '25 Days'), (26, '26 Days'), (27, '27 Days'), (28, '28 Days'), (29, '29 Days')], default=29),
        ),
        migrations.AlterField(
            model_name='company',
            name='after_window_month',
            field=models.IntegerField(choices=[(0, '0 Month'), (1, '1 Month'), (2, '2 Months'), (3, '3 Months'), (4, '4 Months'), (5, '5 Months'), (6, '6 Months'), (7, '7 Months'), (8, '8 Months'), (9, '9 Months'), (10, '10 Months'), (11, '11 Months'), (12, '12 Months')], default=0),
        ),
        migrations.AlterField(
            model_name='company',
            name='before_window_day',
            field=models.IntegerField(choices=[(0, '0 Day'), (1, '1 Day'), (2, '2 Days'), (3, '3 Days'), (4, '4 Days'), (5, '5 Days'), (6, '6 Days'), (7, '7 Days'), (8, '8 Days'), (9, '9 Days'), (10, '10 Days'), (11, '11 Days'), (12, '12 Days'), (13, '13 Days'), (14, '14 Days'), (15, '15 Days'), (16, '16 Days'), (17, '17 Days'), (18, '18 Days'), (19, '19 Days'), (20, '20 Days'), (21, '21 Days'), (22, '22 Days'), (23, '23 Days'), (24, '24 Days'), (25, '25 Days'), (26, '26 Days'), (27, '27 Days'), (28, '28 Days'), (29, '29 Days')], default=0),
        ),
        migrations.AlterField(
            model_name='company',
            name='cancellation',
            field=models.IntegerField(choices=[(0, 'Anytime'), (1, '1 hour'), (3, '3 hours'), (6, '6 hours'), (8, '8 hours'), (12, '12 hours'), (24, '1 day'), (48, '2 days'), (72, '3 days'), (96, '4 days'), (168, '1 week'), (10000, 'never')], default=0),
        ),
    ]
