# Generated by Django 3.1 on 2021-03-19 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0114_auto_20210310_0315'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='stripe_customer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
