# Generated by Django 3.1 on 2021-03-23 03:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0117_auto_20210322_2203'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallary',
            options={'ordering': ('-created',)},
        ),
        migrations.AddField(
            model_name='gallary',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='business_type',
            field=models.CharField(choices=[('product', 'Product Verticle'), ('service', 'Services Verticle')], default='service', max_length=60),
        ),
    ]
