# Generated by Django 3.1.7 on 2021-03-28 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0118_auto_20210322_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyreq',
            name='is_customorder',
            field=models.BooleanField(default=False),
        ),
    ]
