# Generated by Django 3.1.7 on 2021-04-15 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0119_companyreq_is_customorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='stripe_access_token_prod',
            field=models.CharField(blank=True, max_length=260, null=True, unique=True, verbose_name='Stripe Access Token'),
        ),
        migrations.AddField(
            model_name='company',
            name='stripe_user_id_prod',
            field=models.CharField(blank=True, max_length=260, null=True, unique=True, verbose_name='Stripe User Id'),
        ),
    ]
