# Generated by Django 3.1.7 on 2021-05-26 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0121_auto_20210520_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='background',
            field=models.CharField(choices=[('primary', 'primary'), ('carbon', 'carbon'), ('hexagon', 'hexagon'), ('lightblue', 'lightblue'), ('green', 'green')], default='carbon', max_length=200),
        ),
    ]
