# Generated by Django 3.1.7 on 2021-05-26 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0122_auto_20210526_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='background',
            field=models.CharField(choices=[('primary', 'primary'), ('carbon', 'carbon'), ('hexagon', 'hexagon'), ('lightblue', 'lightblue'), ('green', 'green'), ('nicepurple', 'nicepurple')], default='carbon', max_length=200),
        ),
    ]
