# Generated by Django 3.1.7 on 2021-05-28 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0124_auto_20210528_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='background',
            field=models.CharField(choices=[('primary', 'primary'), ('carbon', 'carbon'), ('hexagon', 'hexagon'), ('lightblue', 'lightblue'), ('green', 'green'), ('nicepurple', 'nicepurple'), ('redhexagon', 'redhexagon'), ('hideouteverlasting', 'hideouteverlasting'), ('autumncalming', 'autumncalming')], default='carbon', max_length=200),
        ),
    ]
