# Generated by Django 3.1.7 on 2021-06-08 21:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0125_auto_20210528_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='referedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referred_company', to=settings.AUTH_USER_MODEL),
        ),
    ]
