# Generated by Django 3.1.7 on 2021-07-05 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0126_company_referedby'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='fbproddomainverification',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
