# Generated by Django 3.1 on 2021-03-19 03:28

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0114_auto_20210310_0315'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('description', models.TextField(db_index=True, max_length=250)),
                ('slug', models.SlugField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField()),
                ('request', models.BooleanField(default=False)),
                ('mainimage', models.ImageField(blank=True, upload_to=products.models.get_company_image_folder)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_offered', to='business.company')),
            ],
            options={
                'verbose_name': 'products',
                'verbose_name_plural': 'products',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='GallaryProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photos', models.ImageField(upload_to='companies/gallary/product/photos')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_gallary', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='addOnProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(db_index=True, max_length=250)),
                ('slug', models.SlugField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField()),
                ('mainimage', models.ImageField(blank=True, upload_to=products.models.get_company_image_folder)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addon_product', to='products.product')),
            ],
        ),
    ]
