# Generated by Django 3.1 on 2021-03-23 04:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210322_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='addonproducts',
            name='name',
            field=models.CharField(db_index=True, default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
