# Generated by Django 3.1 on 2021-03-23 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210323_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('CA', 'CA'), ('US', 'US')], db_index=True, default='CA', max_length=200),
        ),
    ]
