# Generated by Django 3.1 on 2021-03-24 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainProductDropDown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placeholder', models.CharField(db_index=True, max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='dispatch',
            field=models.IntegerField(choices=[(0, 'Dispatch right away'), (1, '1 Day'), (2, '2 Days'), (3, '3 Days'), (4, '4 Days'), (5, '5 Days'), (6, '6 Days'), (7, '7 Days'), (8, '8 Days'), (9, '9 Days'), (10, '10 Days'), (11, '11 Days'), (12, '12 Days'), (13, '13 Days'), (14, '14 Days'), (15, '15 Days'), (16, '16 Days'), (17, '17 Days'), (18, '18 Days'), (19, '19 Days'), (20, '20 Days'), (21, '21 Days'), (22, '22 Days'), (23, '23 Days'), (24, '24 Days'), (25, '25 Days'), (26, '26 Days'), (27, '27 Days'), (28, '28 Days'), (29, '29 Days')], default=0),
        ),
        migrations.CreateModel(
            name='ProductDropDown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('dropdown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_dropdown', to='products.mainproductdropdown')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_dropdown', to='products.product')),
            ],
        ),
        migrations.AddField(
            model_name='mainproductdropdown',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_maindropdown', to='products.product'),
        ),
    ]
