# Generated by Django 3.1 on 2021-03-24 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20210324_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(db_index=True, max_length=70000),
        ),
    ]
