# Generated by Django 3.1 on 2021-03-24 22:46

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20210324_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addonproducts',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
