# Generated by Django 3.1 on 2021-03-25 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20210325_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addonproducts',
            name='description',
            field=models.TextField(blank=True, db_index=True, max_length=200, null=True),
        ),
    ]
