# Generated by Django 3.1.7 on 2021-03-29 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20210329_0359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addonproducts',
            name='is_multiple',
        ),
        migrations.RemoveField(
            model_name='addonproducts',
            name='is_required',
        ),
        migrations.AddField(
            model_name='product',
            name='isaddon_multiple',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='isaddon_required',
            field=models.BooleanField(default=True),
        ),
    ]
