# Generated by Django 3.1.7 on 2021-04-16 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
    ]
