# Generated by Django 3.1.7 on 2021-04-16 22:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.CITIES_CITY_MODEL),
        ('products', '0024_order_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='city2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.CITIES_CITY_MODEL),
        ),
    ]
