# Generated by Django 3.1.7 on 2021-04-16 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0011_auto_20180108_0706'),
        ('products', '0025_order_city2'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cities.region'),
        ),
    ]
