# Generated by Django 3.1.7 on 2021-04-17 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0011_auto_20180108_0706'),
        ('products', '0026_order_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='city2',
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, max_length=17, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cities.region', verbose_name='State or Province'),
        ),
    ]
