# Generated by Django 3.1.7 on 2021-04-17 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_auto_20210417_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_international',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_local',
            field=models.BooleanField(default=False),
        ),
    ]
