# Generated by Django 3.1.7 on 2021-04-17 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_auto_20210417_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Address'),
        ),
    ]
