# Generated by Django 3.1.7 on 2021-04-18 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0120_auto_20210415_1334'),
        ('products', '0033_order_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='business.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='slug',
            field=models.SlugField(default='O-2', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
