# Generated by Django 3.1.7 on 2021-04-20 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0036_auto_20210419_2352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcategory',
            old_name='services',
            new_name='products',
        ),
    ]
