# Generated by Django 3.1.7 on 2021-04-23 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0038_auto_20210422_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainproductdropdown',
            name='sublabel',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
