# Generated by Django 3.1.7 on 2021-04-24 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0039_auto_20210422_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='addon',
        ),
        migrations.DeleteModel(
            name='addOnProducts',
        ),
    ]
