# Generated by Django 3.1.7 on 2021-04-24 04:44

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0040_auto_20210424_0018'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', tinymce.models.HTMLField()),
            ],
        ),
        migrations.CreateModel(
            name='QuestionModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(db_index=True, max_length=1500)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_questions', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='MultipleImageAttachments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photos', models.ImageField(blank=True, upload_to='companies/answers/orders/photos')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_attachments', to='products.answermodels')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.AddField(
            model_name='answermodels',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_questionresponse', to='products.questionmodels'),
        ),
    ]
