# Generated by Django 3.1.7 on 2021-04-24 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0041_auto_20210424_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionmodels',
            name='question',
            field=models.CharField(db_index=True, max_length=400),
        ),
    ]
