# Generated by Django 3.1.7 on 2021-04-24 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0042_auto_20210424_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionmodels',
            name='attachment_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questionmodels',
            name='is_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questionmodels',
            name='provide_attachment',
            field=models.BooleanField(default=False),
        ),
    ]
