# Generated by Django 3.1.7 on 2021-04-24 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0120_auto_20210415_1334'),
        ('products', '0043_auto_20210424_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items_company', to='business.company'),
        ),
    ]
