# Generated by Django 3.1.7 on 2021-04-24 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0044_orderitem_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionmodels',
            name='placeholder',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
