# Generated by Django 3.1.7 on 2021-04-25 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0046_answermodels_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='pendingapproval',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='dispatch',
            field=models.IntegerField(choices=[(0, 'Ready for delivery right away'), (1, '1 Day'), (2, '2 Days'), (3, '3 Days'), (4, '4 Days'), (5, '5 Days'), (6, '6 Days'), (7, '7 Days'), (8, '8 Days'), (9, '9 Days'), (10, '10 Days'), (11, '11 Days'), (12, '12 Days'), (13, '13 Days'), (14, '14 Days'), (15, '15 Days'), (16, '16 Days'), (17, '17 Days'), (18, '18 Days'), (19, '19 Days'), (20, '20 Days'), (21, '21 Days'), (22, '22 Days'), (23, '23 Days'), (24, '24 Days'), (25, '25 Days'), (26, '26 Days'), (27, '27 Days'), (28, '28 Days'), (29, '29 Days')], default=0),
        ),
    ]
