# Generated by Django 3.1.7 on 2021-04-25 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0048_order_shipped'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderplaced',
            field=models.BooleanField(default=False),
        ),
    ]
