# Generated by Django 3.1.7 on 2021-04-28 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0050_auto_20210427_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dateshipped',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
