# Generated by Django 3.1.7 on 2021-04-28 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0051_order_dateshipped'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='dateshipped',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
