# Generated by Django 3.1.7 on 2021-04-29 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0053_auto_20210427_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='recieveupdates',
            field=models.BooleanField(default=True),
        ),
    ]
