# Generated by Django 3.1.7 on 2021-05-02 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0055_auto_20210502_0148'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleImageOrderAttachments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photos', models.ImageField(blank=True, upload_to='companies/answers/orders/photos')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('orderitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imageattachment_orderitems', to='products.orderitem')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_imageattachments', to='products.questionmodels')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.AlterModelOptions(
            name='answermodels',
            options={'ordering': ('-created',)},
        ),
        migrations.AddField(
            model_name='answermodels',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='MultipleImageAttachments',
        ),
    ]
