# Generated by Django 3.1.7 on 2021-05-02 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0057_auto_20210502_0154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionmodels',
            name='attachment_required',
        ),
        migrations.RemoveField(
            model_name='questionmodels',
            name='provide_attachment',
        ),
        migrations.AddField(
            model_name='questionmodels',
            name='retrievetype',
            field=models.IntegerField(choices=[(0, 'Free text'), (1, 'Image Attachment')], default=0),
        ),
    ]
