# Generated by Django 3.1.7 on 2021-05-02 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0059_auto_20210502_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multipleimageorderattachments',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_imageattachments', to='products.answermodels'),
        ),
    ]
